version: "3.8"
volumes:
  squid_data: {}
services:
  squid:
    image: squid
    build:
      dockerfile: Dockerfile
      context: .
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.80'
          memory: 2048M
        reservations:
          memory: 2048M
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 3128:3128
    container_name: squid
    volumes:
    - squid_data:/var/spool/squid
    environment: 
      - TZ=America/Sao_Paulo
    # healthcheck:
    #   test: /usr/bin/squidclient -h 127.0.0.1  mgr:carp || exit 1
    #   interval: 20s
    #   timeout: 5s
    #   retries: 3
